apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ .Values.label.app }}
  name: is-{{ .Values.label.app }}
spec:
  lookupPolicy:
    local: {{ .Values.image.lookupPolicy.policy }}
  tags:
  - annotations:
      openshift.io/imported-from: {{ .Values.image.repository }}
    from:
      kind: DockerImage
      name: {{ .Values.image.repository }}:{{ .Values.image.tag }} 
    importPolicy:
      scheduled: {{ .Values.image.importPolicy.scheduled }}
    name: {{ .Values.image.tag }}
    referencePolicy:
      type: {{ .Values.image.referencePolicy.type }}
