apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.label.app }}
spec:
  ports:
    - name: '3000-{{ .Values.service.protocol | lower }}'
      protocol: {{ .Values.service.protocol | quote }}
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.containerPort }}
  selector:
    app: {{ .Values.label.app | quote }}
  type: {{ .Values.service.type | quote }}
  sessionAffinity: None
